### PR TITLE
Multiple window_covering fixes

### LINKED ISSUE #120: Lift & tilt are required for absolute positioning at window covering?
I've been testing with window covering device types and have found that I can't add the absolute positioning feature if I only support lift (and position aware lift) or tilt (and position aware tilt).

I can't find at the Matter specification any conformance that force you to use both features if you want to use absolute positioning.

### PR DESCRIPTION
**Pull request by Diegorro98**
When adding `absolute_position` feature and previously added `lift` and `position_aware_lift` **or** `tilt` and `position_aware_tilt`, neither attributes and commands are created. 
Following the Matter specification, should be expected the following attributes and commands

- If I enable `lift`, `position_aware_lift`, `tilt` and `position_aware_tilt`:
  - Attributes:
    - `physical_closed_limit_lift`
    - `current_position_lift`
    - `installed_open_limit_lift`
    - `installed_closed_limit_lift`
    - `physical_closed_limit_tilt`
    - `current_position_tilt`
    - `installed_open_limit_tilt`
    - `installed_closed_limit_tilt`
  - Commands:
    - `go_to_lift_value`
    - `go_to_tilt_value`
- If I enable `lift` and `position_aware_lift` only:
  - Attributes:
    - `physical_closed_limit_lift`
    - `current_position_lift`
    - `installed_open_limit_lift`
    - `installed_closed_limit_lift`
  - Commands:
    - `go_to_lift_value`
- If I enable `tilt` and `position_aware_tilt` only:
  - Attributes:
    - `physical_closed_limit_tilt`
    - `current_position_tilt`
    - `installed_open_limit_tilt`
    - `installed_closed_limit_tilt`
  - Commands:
    - `go_to_tilt_value`
- If I enable `lift` only:
  - Attributes:
    - none
  - Commands:
    - `go_to_lift_value`
- If I enable `tilt` only:
  - Attributes:
    - none
  - Commands:
    - `go_to_tilt_value`

In this pull request I have included a fix where instead of returning with `ESP_ERR_NOT_SUPPORTED` if all the features are not added previously (which is the current behavior), it only returns `ESP_ERR_NOT_SUPPORTED` if none of the features mentioned have been added previously. If at least one is supported, it will create the expected attributes & commands. 
(Fix #120)
~Also performed some formatting at `esp_matter_feature.cpp` at the window_covering namespace~, No longer necessary after some change made in main branch.

I also have found other problems related to window covering cluster:
- The cluster revision for window covering is 6, but the highest cluster revisión for window covering cluster at the Matter 1.0 specifications is 5.

- When a window covering cluster is created `operational_status` it is ignored and the value of `config_status` is set instead.

### CODE REVIEW

**Comment by dhrishi** [comment]
@Diegorro98 Thanks for the PR. We will review it soon.

**Comment by dhrishi** [comment]
@Diegorro98 Some part of the changes here are a part of our internal fix that was raised around 3 days back. I can push that PR now and then you can rebase your PR changes on top of it. Is that okay?

**Comment by dhrishi** [comment]
Done! Please see this commit: https://github.com/espressif/esp-matter/commit/eaa60c345f68f516f1776653581375ceffb0bf60

**Comment by Diegorro98** [comment]
> @Diegorro98 Some part of the changes here are a part of our internal fix that was raised around 3 days back. I can push that PR now and then you can rebase your PR changes on top of it. Is that okay?

Sure, no problem ^^

**Comment by Diegorro98** [comment]
@dhrishi Done!

**Comment by Diegorro98** [comment]
I added one more commit, because I have found that when creating the installed closed limit for tilt when adding the `absolute_position` feature, the value set was the value of `installed_closed_limit_lift` instead of the tilt one.

File: components/esp_matter/esp_matter_feature.cpp [hunk 1]
```diff
@@ -454,36 +454,47 @@ esp_err_t add(cluster_t *cluster, config_t *config)
...
     } else {
-        ESP_LOGE(TAG, "Cluster shall support Position_Aware_Tilt feature");
-        return ESP_ERR_NOT_SUPPORTED;
+        ESP_LOGI(TAG, "Tilt related attributes were not created because cluster does not support Position_Aware_Tilt feature");
     }
 
     if((get_feature_map_value(cluster) & abs_and_lift_feature_map) == abs_and_lift_feature_map) {
 	    command::create_go_to_lift_value(cluster);
+    } else {
+        ESP_LOGI(TAG, "Lift commands were not created because cluster does not support Lift feature");
```
Comment (dhrishi) [inline components/esp_matter/esp_matter_feature.cpp:491]: Why do you think are these prints required? Is it something like it is set/enabled by the user and the data model does not create it?
If that isn't the case, can we remove all the `ESP_LOGI` here?

**Comment by dhrishi** [comment]
LGTM, in general. A minor comment added

File: components/esp_matter/esp_matter_feature.cpp (hunk 1 above)
Comment (Diegorro98) [reply components/esp_matter/esp_matter_feature.cpp:491]: I don't really think that these logs must be there, I wrote because I thought that maybe it was necessary to inform to the user that the commands and/or the attributes were not created, like in another features, but this here, instead of `ESP_LOGE`, which is inadequate because are valid cases, I used `ESP_LOGI`.
Maybe the user should know about from the Matter specification that to get lift/tilt commands are obtained once lift/tilt features are enabled and lift/tilt attributes are enabled by enabling lift/tilt and position aware lift/tilt features. In that case, these logs are not a MUST.

Comment (dhrishi) [reply components/esp_matter/esp_matter_feature.cpp:491]: Ok. Will warning logs `ESP_LOGW` fit better?

Comment (Diegorro98) [reply components/esp_matter/esp_matter_feature.cpp:491]: That's what I thought the first time, but also I thought that it was inadequate too. But now I think that it fits better, yeah.

I'm going to change it right now so it can be pushed.

**Review by dhrishi — APPROVED** [review]

**Comment by dhrishi** [comment]
@Diegorro98 Thank you. We will create an internal change for this PR (with your contribution) and then it will be synced to Github, once the CI and other checks are successful

**Comment by InfiniteYuan** [comment]
LGTM @dhrishi 

Thx @Diegorro98
