### PR TITLE
Do not fail startup if default event loop initialized (CON-561)

### LINKED ISSUE #456: Startup failure if default event loop was already initialised (CON-559)
https://github.com/espressif/esp-matter/blob/915405c0ab9f339710b85027ff587b594e9eb686/components/esp_matter/esp_matter_core.cpp#L944

From my understanding at this line we can just check if creation was successful or underlying method returned ESP_ERR_INVALID_STATE which means that event loop is already created. Am I right or there's some specific reason we need a freshly created event loop to function?

### PR DESCRIPTION
**Pull request by rfortunatov**
In case create event loop returns ESP_ERR_INVALID_STATE it is not necessary to fail startup as of it means that default event loop is already initialized and no additional actions should be done.

Would close #456

### CODE REVIEW

File: components/esp_matter/esp_matter_core.cpp [hunk 1]
```diff
@@ -941,7 +941,7 @@ esp_err_t start(event_callback_t callback, intptr_t callback_arg)
         return ESP_ERR_INVALID_STATE;
     }
```
Comment (shubhamdp) [inline components/esp_matter/esp_matter_core.cpp:942]: Can you please add a comment in code why we are also checking `ESP_ERR_INVALID_STATE`.

Comment (rfortunatov) [reply components/esp_matter/esp_matter_core.cpp:942]: Sure.

**Review by shubhamdp — APPROVED** [review]

**Comment by shubhamdp** [comment]
@rfortunatov PR has been merged, Thanks for the contributions.
